### ISSUE TITLE
Is the french translation abandonned?

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [moritz-weber/mucke#132]
I wanted to contribute to the french translation for mucke, but it seems like there's no glossary, and it seems like it's been a while since anyone touched the translation.

I usually would ask the main translator for that language permission to add terms to the glossary, since that's what shapes the translation, but it doesn't seem like there is any.

So is the french translation abandonned? And if yes, can i add terms to the glossary?

**Comment by moritz-weber** [comment]
Thanks for your interest. I'm not sure about the translation.
The missing glossary could be my fault, since I set up the project on Weblate and haven't really used that tool before.

I don't think, there is something like a main translator here. Feel free to contribute.

If you have tips for me on how to set things in a better way, I'm all ears.

**Comment by Matthieu-LAURENT39** [comment]
The glossary is simply something that indicates how to translate a specific word / term so the translation is more consistent, for exemple `playlist -> liste de lecture`.
If there's no main translator, I'll just add the terms to the glossary myself. I have quite a bit of free time, so i'll probably use that to finish the french translation.
Thanks for the reply!
