### ISSUE TITLE
Quick way to play an album without shuffle

### ISSUE THREAD

**Issue by FriederHannenheim** [moritz-weber/mucke#45]
Currently there's no way to play an album from start to finish without going to the currently playing view and disabling shuffle.
I can think of 2 ways to implement this:
We could introduce a setting to always play songs in order when playing them from an album (i.e. when the user clicks on a song while on the album page). Alternatively we could put buttons for shuffle/playing in order at the top of the album page. Or we could do both. I would prefer doing both since sometimes you may want to start playing songs in an album starting from the selected song.

What do you think of this? I would like to implement this if you don't mind.

**Comment by moritz-weber** [comment]
This is kind of ironic. Everywhere else, albums are played in order from start to finish. Only the `AlbumDetailsPage` has no option for that...

The `PlaylistPage` already supports such a button in the header. You could replace the `AlbumSliverAppBar` in `AlbumDetailsPage` with the more generic `CoverSliverAppBar`. This is something that was on my to-do list anyway. I'd just include a button that plays everything from start to finish in the app bar.

A third option would be to add a playback option to the `BottomSheet` that opens when tapping the hamburger menu of a song.
But, since the `BottomSheet` is already quite large, I'd probably go with your suggestions.

If you need help with the settings for this, feel free to ask. This requires a rough understanding of all the app layers and to my shame, most of it isn't documented :see_no_evil:

**Comment by moritz-weber** [comment]
@FriederHannenheim, I created a couple of solutions for the overlapping text issue. The FloatingActionButton (last one) would probably be the easiest and has the advantage of easy reachability, but I'm not really a fan of those since they often overlap with other content. My favorite would be the fourth one (only the icon and slightly moved down) since the third one with the additional text could overlap with the song info on smaller screens.

![Screenshot_20230129-111022](https://user-images.githubusercontent.com/17176771/215320768-93be8ce1-fe0c-4ffc-a72e-7cd1d3b8f565.png)
![Screenshot_20230129-111413](https://user-images.githubusercontent.com/17176771/215320769-449d28b5-075f-42f1-9998-853dc5729cf4.png)
![Screenshot_20230129-111506](https://user-images.githubusercontent.com/17176771/215320774-d4290df4-1f1b-4907-8f8e-918ffa95fc9f.png)
![Screenshot_20230129-111523](https://user-images.githubusercontent.com/17176771/215320777-2fe8877f-1373-438c-ab06-53e8617b1ce7.png)
![Screenshot_20230129-112122](https://user-images.githubusercontent.com/17176771/215320783-ab9787d6-3527-4a70-95e6-377609ac615a.png)

**Comment by FriederHannenheim** [comment]
I agree that the fourth one is probably the way to go. Though I prefer the look of the 3rd option. Maybe it could be moved down a bit more so it sits below the text.
