### ISSUE TITLE
Missing localization for "Your Playlists" [Localization, German]

### ISSUE THREAD

**Issue by marcofeltmann** [moritz-weber/mucke#90]
**Describe the bug**
Although the device is set to "German" the header of the empty playlist states "Your Playlists" instead of the expected "Deine Wiedergabelisten"

**To Reproduce**
1. Set Device Language to German
1. Fresh install (from F-Droid on LineageOS 20)
2. Configure and refresh library
3. Go to application's Home screen 
4. Everything is in German but the "Your Playlists" section header

**Expected behavior**
Having the "Your Playlists" header translated

**Screenshots**
![mucke-localization-bug](https://github.com/moritz-weber/mucke/assets/19754014/cadae93f-50cb-4206-b37f-431d1244a888)

**Smartphone:**
 - Device: Xiaomi Pocophone F1
 - OS: LineageOS/Android
 - Version: LineageOS 20/Android 13

**Additional context**
I didn't find any keys for this section header in the `l10n` language files, thus I couldn't provide a PR now.

**Comment by moritz-weber** [comment]
Yeah, this is still an issue that is unfortunately not that easy to solve.

The thing is that the title of this playlists widget is customizable: You can change it in the home page settings (the pencil icon). This is also the quick fix, that I would suggest for now. The idea behind this is that you can customize the filter and order settings so that you might want to have multiple widgets with different purposes.

Being customizable, the title is a database entry that is created on the first start of the app at a point where localization is really hard to do. Currently, I see two options:

1) Disable customizability and just use a hard-coded (translatable) string.
2) Rework the database initialization so that localization becomes available there.

I'm not sure yet, which solution I'd prefer...
